application:
  spring:
    security:
      naver:
        client-id: hjXAKRZSt03GUwcpKpVm
        client-secret: cOZFIDt4t9
        authorization-grant-type: authorization_code
        url:
          auth: https://nid.naver.com
          api: https://openapi.naver.com
          redirect-uri: http://localhost:8080/api/auth/naver



      kakao:
        client-id: 2af74a5e3cde12fe79d5827347c814a2
        url:
          auth: https://kauth.kakao.com
          api: https://kapi.kakao.com




      jwt:
        secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K




